from typing import Any

logger: Any

class Error(Exception):
    message: Any = ...
    def __init__(self, msg: str = ...) -> None: ...

class ParsingError(Error):
    filename: Any = ...
    errors: Any = ...
    def __init__(self, filename: Any) -> None: ...
    def append(self, lineno: Any, line: Any) -> None: ...

class MissingSectionHeaderError(ParsingError):
    filename: Any = ...
    lineno: Any = ...
    line: Any = ...
    def __init__(self, filename: Any, lineno: Any, line: Any) -> None: ...

section_header: Any
option_start: Any
leading_blank_lines: Any

def parse(fp: Any, fpname: Any, exp_globals: Any = ...): ...
