import zc.buildout
from typing import Any, Optional
from zc.buildout.easy_install import realpath as realpath

class ChecksumError(zc.buildout.UserError): ...

class Download:
    directory: Any = ...
    cache: Any = ...
    namespace: Any = ...
    offline: Any = ...
    fallback: Any = ...
    hash_name: Any = ...
    logger: Any = ...
    def __init__(self, options: Any = ..., cache: int = ..., namespace: Optional[Any] = ..., offline: int = ..., fallback: bool = ..., hash_name: bool = ..., logger: Optional[Any] = ...) -> None: ...
    @property
    def download_cache(self): ...
    @property
    def cache_dir(self): ...
    def __call__(self, url: Any, md5sum: Optional[Any] = ..., path: Optional[Any] = ...): ...
    def download_cached(self, url: Any, md5sum: Optional[Any] = ...): ...
    def download(self, url: Any, md5sum: Optional[Any] = ..., path: Optional[Any] = ...): ...
    def filename(self, url: Any): ...

def check_md5sum(path: Any, md5sum: Any): ...
def remove(path: Any) -> None: ...
def locate_at(source: Any, dest: Any): ...
