from typing import Any

__metaclass__ = type

class PackageFinder:
    @classmethod
    def find(cls, where: str = ..., exclude: Any = ..., include: Any = ...): ...

class PEP420PackageFinder(PackageFinder): ...

find_packages: Any
find_namespace_packages: Any

def setup(**attrs: Any): ...

class Command:
    __doc__: Any = ...
    command_consumes_arguments: bool = ...
    def __init__(self, dist: Any, **kw: Any) -> None: ...
    def ensure_string_list(self, option: Any) -> None: ...
    def reinitialize_command(self, command: Any, reinit_subcommands: int = ..., **kw: Any): ...

class sic(str): ...
