name: python package

on: [push]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.12', python-version: '3.12', os: ubuntu-latest, tox: py312-buildout_current}
          - {name: '3.11', python-version: '3.11', os: ubuntu-latest, tox: py311-buildout_current}
          - {name: '3.10', python-version: '3.10', os: ubuntu-latest, tox: py310-buildout_current}
          - {name: '3.9', python-version: '3.9', os: ubuntu-latest, tox: py39-buildout_2_9_2,py39-buildout_current}
          - {name: '3.8', python-version: '3.8', os: ubuntu-latest, tox: py38-buildout_2_9_2,py38-buildout_current}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tox
        run: |
          cd server
          pip install tox
          tox
        env:
          TOXENV: ${{ matrix.tox }}
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: server/coverage.xml
        if: matrix.python-version == '3.11'
