name: python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tox on 3.6
        run: |
          cd server
          pip install tox
          tox
        env:
          TOXENV: py36-buildout_2_9_2,py36-buildout_current
        if: matrix.python-version == '3.6'
      - name: Run Tox on 3.7
        run: |
          cd server
          pip install tox
          tox
        env:
          TOXENV: py37-buildout_2_9_2,py37-buildout_current
        if: matrix.python-version == '3.7'
      - name: Run Tox on 3.8
        run: |
          cd server
          pip install tox
          tox
        env:
          TOXENV: py38-buildout_2_9_2,py38-buildout_current
        if: matrix.python-version == '3.8'
      - name: Run Tox on 3.9
        run: |
          cd server
          pip install tox
          tox
        env:
          TOXENV: py39-buildout_2_9_2,py39-buildout_current
        if: matrix.python-version == '3.9'
      - name: Run Tox on 3.10
        run: |
          cd server
          pip install tox
          tox
        env:
          TOXENV: py310-buildout_current
        if: matrix.python-version == '3.10'
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: server/coverage.xml
        if: matrix.python-version == '3.10'
